export {default as Hero} from "./hero/hero"
export {default as Nav} from "./nav/nav.jsx"
export {default as Themes} from "./theme/themes.js"
export {default as Pildoras} from "./sliderPildoras/Pildoras.jsx"
export {default as SobreMi} from "./sobreMi/SobreMi.jsx"
export {default as Proyectos} from "./sliderProyectos/Proyectos.jsx"
export {default as TargetasPro} from "./tarjetaProyecto/TarjetaProyecto.jsx"
export {default as Footer} from "./footer/Footer.jsx"